name = "s2d2"
main = "build/worker/shim.mjs"
compatibility_date = "2025-07-11"

[observability.logs]
enabled = true

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
spam_score_threshold = "5.0"

[[kv_namespaces]]
binding = "WEBHOOK_URLS"
id = "2db7445c0b6548d6aa73fc34bafe72d1"

[vars]
spam_score_threshold = "5.0"

[[routes]]
pattern = "https://s2d2.jizi.jp"
custom_domain = true